config/routes.rb
Rails.application.routes.draw do
  
  root 'trainings#index'
  

  devise_for :users

  resources :users, only: [:index, :show] 

  resources :trainings do 
    resources :partners, only: [:create, :destroy]
    get 'search', on: :collection
  end

  get '/about', to: 'about#index', as: 'about'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/partner.rb
class Partner < ApplicationRecord
    validates :user_id, uniqueness: { scope: :training_id }

    belongs_to :user
    belongs_to :training

    scope :upcoming, ->{order(created_at: :desc ) }

    def self.upcoming2(user_id)
        if user_id
          where(user_id: user_id)
        end
    end
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  

  scope :public?, -> { where(:public => true)}
  scope :ordered_by_most_recent, ->(limit:10){order(created_at: :desc ) }
  scope :upcoming, -> { where.not(:status => "canceled").or(where.not(:status => "complete"))}
  has_many :partners, dependent: :destroy

  

  def self.search(search)
    if search
      where(["zipcode LIKE ?" , "%#{search}%"])
    else
      all
    end
  end

  #def self.upcoming()
   # if user_id
    #  where(user_id: user_id)
   # end
  #end


 # handle status
 enum status: [:open, :full, :complete, :canceled]
#  def status
#   @status ||= TrainingStatus.new(read_attribute(:status))
#  end  

  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include Gravtastic
  gravtastic
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_many :trainings
  has_many :partners, dependent: :destroy

  

  

  

 
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController


    def show
    end
    def index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
    end


end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

    

    def create
      @partner = current_user.partners.new(training_id:  params[:training_id])
      t = @partner.save
      if t
        redirect_to request.referrer, notice: 'partner was successfully created.'
      else
        redirect_to request.referrer, alert: @partner.errors.full_messages.join('. ').to_s
      end
    end
    def destroy
      partner = Partner.find_by(id: params[:id], user: current_user, training_id: params[:training_id])
      if partner
        partner.destroy
        redirect_to request.referrer, notice: 'You remove from the this training.'
      else
        redirect_to request.referrer, alert: 'You cannot remove from this training.'
      end
    end
    def show
      @partner = Partner.find(params[:id])
    end
  end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :authenticate_user!


  # GET /trainings
  # GET /trainings.json
  def index
        @training = Training.new
        public_trainings
        #Rails.logger.info "DEBUG:: "+public_trainings.to_s()
    
    end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])
    partners
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @training.status = 0;
    
     
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])

  end

  # POST /trainings
  # POST /trainings.json
  def create
    @user=current_user
    str = training_params[:date].gsub(/\s+/m, ' ').strip.split(" ")
    r=str[1]+str[0]
    date=r.to_date()
    @training =@user.trainings.new(training_params)
    @training.status = 0
    @training.date=date
    respond_to do |format|
      if @training.save
        format.html { redirect_to trainings_path, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    @user=current_user
    @training =@user.trainings.find(params[:id])
    respond_to do |format| 
      if @training
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # trainings#search
  def search
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @term = params[:search] 
      # TODO change title to zipcode
      @results = Training.all.where("lower(title) LIKE :search", search: @term.downcase )  
      @users_results = User.all.where("lower(name) LIKE :search", search: @term.downcase )
        
    end
end

  private

    # partners
    def partners
      @partners = Partner.where(training_id: params[:id])
      if @partners == []
       @partners = Partner.new
      end
    end
    # training public list
    def public_trainings
      @public_trainings ||= users_public_trainings.ordered_by_most_recent
    end

    def users_public_trainings
      Training.where(public: true).or(Training.where(user_id: current_user.id))
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:title, :date, :duration, :participants, :user_id, :location, :public, :details, :training_type, :zipcode)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @users = User.all
    end
  
    def show
      @user = User.find(params[:id])
      @trainings = @user.trainings.ordered_by_most_recent
      @partners_tranings =  @user.partners.upcoming2(@user.id)
      p "######################"
      @upcoming_tranings=Array.new
      i = 0
      @partners_tranings.each{|partner, | 
      @upcoming_tranings[i] = Training.where(id:partner.training_id).upcoming
        i+=1
        p i
      }
      p @upcoming_tranings
    
      end
  
 ##   def pending_friends
     # @users = current_user.pending_friends
    #end
  
    #def friend_requests
   #   @users = current_user.friend_requests
  #  end
  end

app/helpers/application_helper.rb
module ApplicationHelper

    def join_to_training(training)
        partner = Partner.find_by(training_id: training.id, user_id: current_user.id)
        if partner
          unless  partner.id.nil?
            link_to('Remove Me', training_partner_path(id: partner.id, training_id: training.id), method: :delete, class: 'btn  btn-sm justify-content-center d-flex mx-auto')
          end
        else
          link_to('Join Me 🏃🏽‍♀️', training_partners_path(training_id: training.id, ), method: :post, class: 'btn  btn-sm justify-content-center d-flex mx-auto')
        end
    end
  
    def create_google_map_link(location) # TODO: Add zipcode to url
      url="https://www.google.com/maps/search/?api=1&query="+location.to_s
      
      link_to(location, url , class: ' d-flex mx-auto') 
    end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/about/index.html.erb
<h1>about</h1>

app/views/layouts/_footer.html.erb
<footer class="mastfoot mt-auto fixed-bottom">
    <div class="inner">
      <p>by <a class="mastfoot" href="https://github.com/adimola4">Adi Mola</a>.</p>
    </div>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunWithMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'application' %>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
  </head>

  <body class="bg-h-45 ">
     <div class="wrapper cover-container d-flex w-100 h-100 p-3 mx-auto flex-column bg-l-100">
      <header class="header">
        <%= render 'layouts/nav/nav' %>
      </header>
      
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
     
           <main role="main" class="flex-shrink-0">
                 <%= yield %>

           </main>
               <%= render 'layouts/footer' %>

     </div>

    <%# Bootstrap %>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    </div>
  </body>
</html>

app/views/layouts/nav/_nav.html.erb
<nav class="navbar navbar-expand-lg fixed-top  bg-h-0">
  <strong>
    <%= link_to "🏃🏽 Run With Me 🏃🏽‍♀️", root_path, class: "navbar-brand mr-auto mr-lg-0"%>
  </strong>
  <button class="navbar-toggler  p-0 border-0 nav-ham float-right" type="button" data-toggle="collapse" data-target="#navbarNav" >
    <span class=""><i class="fas fa-bars"></i></span>
  </button>
  <div class="collapse navbar-collapse o-10 text[#ff5e6c]" id="navbarNav">
    <ul class=" navbar-nav mr-auto ul-nav" id="nav-ul">
      
      <%= form_tag search_trainings_path, :method => 'get' , class: 'form-inline my-1 my-sm-0 h-25 d-inline-block'  do%>
      <%= text_field_tag :search, params[:search], class:"form-control mr-0 ml-3 h-25 ", placeholder:"Zipcode"%>
        <%= submit_tag "search", class:"btn btn-outline-success p-1 ml-0 "%>
      <%end%>
    
      </li>

      <% if current_user %>
       <li class="stick-right">
       <ul class="navbar-nav ">
          <li class="nav-item dropdown   ">
                <a class=" dropdown-toggle text[#ff5e6c]" href="#" id="dropdown-nav" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%=current_user.name%></a>
                <ul class="dropdown-menu " aria-labelledby="dropdown-nav">
                  <li><%= link_to(current_user, html_options = {class:'dropdown-item'}) do%>
                      <strong>Profile</strong>
                  <%end%></li>
                 <li> <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item"%></li>
                 <li> <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item"%> </li>
                </ul>
                <%= image_tag current_user.gravatar_url, :class => "gravatar " %>
          </li>
            <%# <div id="collapse-hide">
            <li class="nav-item ">
            <%= link_to "Add Training", new_user_session_path, class: "nav-link "%>
        <%#  </li>%
         </div>%>
        </ul>
        </li>
       
      <% else %>
      <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
        </li>
        <% end %>
       
    </ul>
   
  </div>
  
</nav>

app/views/partners/_partner.html.erb
<div class="card col-4  card-partner ">
            <%= link_to(@training.user, html_options = {class:'btn-link a-card-partner'}) do%>
               <%=image_tag("/assets/images/avatar.jpg",class: "avatar-partner rounded-circle", size: "104x104", alt: "avatar")%>
                <div class="col-md-4">
                    <p>
                    <h4 class="card-title partner-name-title">id:<%= partner.user_id %></h4></p>
                    <p class="card-subtitle mb-2 text-muted ">Famous Actor</p>
               </div>
            <%end%>        
 </div>

app/views/trainings/_form.html.erb
<div class=" mx-auto multistep-card">
      <h2 class="multistep-card-title">Creat new training</h2>
      <ul id="progressbar">
          <li class="active">Basic info</li>
          <li>Date % Location</li>
          <li>More Details</li>
          <li>Review</li>
      </ul>
      
    </div>
    <div class="form-outer">
    <%= form_with(model: training, local: true, id:"newtraining") do |form| %>
      <% if training.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>
        <ul>
          <% training.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        </div>
      <% end %>
          <fieldset class="step slide-step mx-auto fieldset">
              <div class="step-card-title">Basic Info:</div>
              <div class="form-group training-group">
                  <%= form.label :title, class:"label"%>
                  <%= form.text_field :title , class:"form-control", placeholder:"running 5km..." %>
              </div>
              <div class="form-group training-group">
                  <%= form.label :training_type, class:"label" %>
                  <br/>
                  <%= form.select(:training_type,[['Running', 1], ['Walkd', 2],['Strength',3]],class:"form-control") %>
              </div>
              <div class="form-group training-group">
                  <%= form.label :participants, class:"label" %>
                  <%= form.number_field :participants, class:"form-control", placeholder:"how much partners?" %>
              </div>
               <input type="button" name="next" class="btn btn-info action-button next" value="Next"/>
          </fieldset>
          <fieldset class="step mx-auto ">
            <div class="step-card-title">time & location</div>
            <div class="form-group training-group">
              <%= form.label :date, class:"label" %>
              <%= form.text_field :date, id:"training_date", width: 160%>
              <script>
                  $('#training_date').datetimepicker({ footer: true, modal: true });
              </script>
            </div>
             <div class="form-group training-group">
                <%= form.label :location, class:"label" %>
                <%= form.text_field :location, class:"form-control", placeholder:"11 name st, city, state" %>
            </div>
            <div class="form-group training-group">
                <%= form.label :zipcode, class:"label" %>
                <%= form.number_field :zipcode, class:"form-control", placeholder:"123456...", autocomplete:"zipcode"%>
            </div>
            <div class="field btns">
                  <button type="button" name="previous" class="btn btn-info  previous action-button">Previous</button>
                  <button type="button" name="next" class="btn btn-info next action-button">Next</button>
            </div>
          </fieldset>
          <fieldset class="step mx-auto ">
            <div class="step-card-title">More info</div>
            <div class=" form-group training-group">
                <%= form.label :details, class:"label" %>
                <%= form.text_area  :details,class:"form-control", placeholder:"we going to run 5 mph....." %>
            </div>
            <div class=" form-group custom-control custom-checkbox">
                <%= form.check_box  :public, class:"custom-control-input " %>
                <%= form.label :public, class:"custom-control-label label"%>
            </div>
            <div class="field btns">
               <button type="button" name="previous" class="btn btn-info  previous action-button">Previous</button>
                  <button type="button" name="next" class="btn btn-info next action-button">Next</button>
           </div>
          </fieldset>
          <fieldset class="step mx-auto ">
            <div class="step-card-title">Review Details:</div>
              
              <div class="field btns">
                <button type="button" name="previous" class="btn btn-info  previous action-button">Previous</button>
                <button type="submit" name="submit" class="btn btn-info  submit action-button ">Next</button>
              </div>
          </fieldset>
        </form>
    </div>
</div>


</div>
<% end %>

<script type="text/javascript">
    var current_fs, next_fs, previous_fs; //fieldsets
    var left, opacity, scale; //fieldset properties which we will animate
    var animating; //flag to prevent quick multi-click glitches

    $(".next").click(function(){
      
      if(animating) return false;
      animating = true;
      current_fs = $(this).parent("fieldset");
      next_fs = $(this).parent().next();
      console.log(JSON.stringify(current_fs))
      console.log(JSON.stringify(next_fs))

      //activate next step on progressbar using the index of next_fs
      $("#progressbar li").eq($("fieldset").index(next_fs)).addClass("active");
      
      //show the next fieldset
      next_fs.show(); 
      //hide the current fieldset with style
      $(current_fs).animate({opacity: 0}, {
        step: function(now, mx) {
          //as the opacity of current_fs reduces to 0 - stored in "now"
          //1. scale current_fs down to 80%
          scale = 1 - (1 - now) * 0.2;
          //2. bring next_fs from the right(50%)
          left = (now * 50)+"%";
          //3. increase opacity of next_fs to 1 as it moves in
          opacity = 1 - now;
          current_fs.css({
            'transform': 'scale('+scale+')',
            'position': 'absolute'
          });
          next_fs.css({'left': left, 'opacity': opacity});
        }, 
        duration: 800, 
        complete: function(){
          current_fs.hide();
          animating = false;
        }, 
        //this comes from the custom easing plugin
        easing: 'easeInOutBack'
      });
    });

    $(".previous").click(function(){
      if(animating) return false;
      animating = true;
      
      current_fs = $(this).parent();
      previous_fs = $(this).parent().prev();
      
      //de-activate current step on progressbar
      $("#progressbar li").eq($("fieldset").index(current_fs)).removeClass("active");
      
      //show the previous fieldset
      previous_fs.show(); 
      //hide the current fieldset with style
      current_fs.animate({opacity: 0}, {
        step: function(now, mx) {
          //as the opacity of current_fs reduces to 0 - stored in "now"
          //1. scale previous_fs from 80% to 100%
          scale = 0.8 + (1 - now) * 0.2;
          //2. take current_fs to the right(50%) - from 0%
          left = ((1-now) * 50)+"%";
          //3. increase opacity of previous_fs to 1 as it moves in
          opacity = 1 - now;
          current_fs.css({'left': left});
          previous_fs.css({'transform': 'scale('+scale+')', 'opacity': opacity});
        }, 
        duration: 800, 
        complete: function(){
          current_fs.hide();
          animating = false;
        }, 
        //this comes from the custom easing plugin
        easing: 'easeInOutBack'
      });
    });

    $(".submit").click(function(){
      return false;
    })

</script>

app/views/trainings/_past_training.html.erb
<div class="col-12 col-md-6">
    <%# add emoji %>
  <div class="card card1 " >
    <%=image_tag("/assets/images/avatar.jpg",class: "card-img1 rounded-circle", size: "16x10", alt: "avatar")%>
    
    <div class="card-img">
        <%= link_to(training.user, html_options = {class:'name-btn   btn-sm '}) do%>
        <strong><%= training.user.name %></strong>
          <%end%>
    <small class="text-muted cat">
      <i class="far fa-clock text-info"></i> <%= training.date.strftime("%Y/%m/%d")  %>
      <i class="fas fa-users text-info"></i> <%= training.participants %>
    </small>
    </div>
    <div class="card-body">
    <h4 class="card-title">What we gonna do? <%= training.title%></h4>
    <p> Where? <%= training.location %>, <%= training.zipcode %>.</p>
    <p> Duration: <%= training.duration %></p>
    </div>
    <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
        <div class="views">last modified: <%= training.created_at.strftime("%Y/%m/%d") %> 
    </div>
   
  </div>
</div>
</div>
      
      

app/views/trainings/_training.html.erb
<div class="col-sm-12 col-md-12 col-lg-6">
  <div class="card card1" >
    <%=image_tag("/assets/images/avatar.jpg",class: "card-img1 rounded-circle", size: "16x10", alt: "avatar")%>
    <div class="card-img">
        <%= link_to(training.user, html_options = {class:'name-btn   btn-sm '}) do%>
        <strong><%= training.user.name %></strong>
          <%end%>
    <small class="text-muted cat">
      <i class="far fa-clock text-info"></i> <%= training.date.strftime("%Y/%m/%d")  %>
      <i class="fas fa-users text-info"></i> <%= training.participants %>
    </small>
    </div>
    <div class="card-body">
    <h4 class="card-title">What we gonna do? <%= training.title%></h4>
    <p> Where? <%= training.location %>, <%= training.zipcode %>.</p>
    <p> Duration: <%= training.duration %></p>
    <% date_diff = Date.current() - Date.parse(training.date.to_s())%>
    <% if date_diff < 0 %>

        <%= join_to_training(training) %> 
        </div>
        <div class="card-footer text-muted d-flex justify-content-between bg-transparent border-top-0">
            <div class="views">last modified: <%= training.created_at.strftime("%Y/%m/%d") %> 
        </div>
        <div class="stats cat">
          <i class="far fa-eye"></i> 1347
          <i class="far fa-comment"></i> 12
        </div>
    <%else%>
      <div><strong>
      done
        ✅   ✅   ✅</strong> </div>

    <% end%>
    
  </div>
</div>
</div>
      
      

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
  
    <div class="align-items-start">

    <%= render template:"trainings/new", training: @training %>
    </div>
    <hr/>
    <article class="row align-items-center">
      <h3 class="mx-auto">
        Recent trainings
      </h3>
    
        <div class="row ">
            <%= render @public_trainings %>
        </div>
    
    </article>

app/views/trainings/new.html.erb
<h4 class="align-self-center mx-auto">New Training</h4>

<%= render 'form', training: @training %>

app/views/trainings/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @training.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @training.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @training.duration %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @training.participants %>
</p>
<p>
  <strong>Location:</strong>
  <%= @training.location %>
</p>
<p>
  <strong>Zipcode:</strong>
  <%= @training.zipcode %>
</p>
<p>
  <strong>Status:</strong>
  <%= @training.status %>
</p>
<p>
  <strong>Public:</strong>
  <%= @training.public %>
</p>
<div class="row ">
      <%= render @partners %>
</div>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>

app/views/users/_upcoming.html.erb
<table class="table table-bordered table-sm upcoming-table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Title</th>
      <th scope="col">Location</th>
      <th scope="col"></th>
     </tr>
  </thead>
  <tbody class="table_body">
      <%  @upcoming_tranings.each do |training| %>
            <tr>

            <th scope="row"> <%= training[0].date.strftime("%m/%d/%Y")%></th>
            
              <td>
                <%= training[0].title%>
              </td>
              <td>
                <%= create_google_map_link(training[0].location)%>
              </td>
              <% if current_user == training[0].user_id %>
              <td>
              <%#לשנות את זה לפנוקציה כך שאני לא יכול לערוך אימון של מישהו אחר%>
                <%= link_to ' <button type="button" class="btn btn-success"  data-toggle="tooltip" data-placement="top" title="More details/Edit"><i class="fas fa-edit"></i></button>'.html_safe, edit_training_path(training[0].id)%> 
              </td>
              <td>
               <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe , training_path(training),
                  method: :delete,
                  class: "btn btn-danger",
                  data: { confirm: 'Are you sure?' } %></td>
              <%else%>
              <td>
                <%= link_to ' <button type="button" class="btn btn-success"  data-toggle="tooltip" data-placement="top" title="More details"><i class="fas fa-edit"></i></button>'.html_safe, training_path(training[0].id)%> 
              </td>
              <%#<td>
              <%# <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe , training_partner_path(training),
                 <%# method: :delete,
                  <%#class: "btn btn-danger",
                 <%# data: { confirm: 'Are you sure?' } %></td>
              <%end%>
              
            </tr>
          <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<div class="card col-md-12 px-0 card-user">
        <img class="card-img-top img-responsive cover-img" src="/assets/images/woman-running.jpg" >
        <div class="card-body card-body1">
            <%=image_tag("/assets/images/avatar.jpg",class: "avatar rounded-circle", size: "150x150", alt: "avatar")%>
            <h3 class=" card-title user-name-title"><%=user.name %><a href="#" class="user-name-title-info btn btn-outline-info outline-btn"><span><i class="fas fa-ellipsis-v"></i></span></a></h3>
            <h4 class="card-subtitle mb-2 text-muted">Famous Actor</h4>
            <p class="card-text">... </p>
        </div>
 </div>

app/views/users/index.html.erb
<section class="form-auth text-canter container col-4">
            <table>
            <tr>
            <th>User</th>
            <th>See profile</th>
            <th colspan="2">Action</th>
            </tr>
            <% @users.each do |user| %>
                <% if current_user != user %>
                    <tr>
                        <td>
                        <%= user.name %>
                        <span class="profile-link">
                        </td>
                        <td><%= link_to 'See Profile',  user_path(user), class: 'profile-link' %></td>
                        
                        <% if current_user.friend?(user) %>
                            <td><%= link_to '<button type="button">Unfriend</button>'.html_safe, friendship_path(user), method: :delete, data: { confirm: "Are you sure you want to Unfriend"} %></td>
                        <% elsif current_user.pending_friends.include?(user) %>
                            <td><%= link_to "Request pending #{user.name}",  user_path(user), class: 'profile-link' %> </>               
                        <% elsif current_user.friend_requests.include?(user) %>
                            <td><%= link_to '<button type="button">Accept</button>'.html_safe, friendship_confirm_path(user), method: :post %>    </td>     
                            <td><%= link_to '<button type="button">Reject</button>'.html_safe, friendship_reject_path(user), method: :delete %>   </td>      
                        <% else %>
                            <td><%= link_to '<button type="button">Send Request</button>'.html_safe, friendships_path(user_id: current_user.id, friend_id: user.id), method: :post %></td>
                        <% end %>
                        </span>        
                    </tr>
                    <% end %>
                <% end %>



</table>







</section>